#!/usr/bin/env python3
"""Render Codex's single config.toml from local AID2E fragments."""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path


CODEX_DIR = Path(__file__).resolve().parent
BASE_CONFIG = CODEX_DIR / "config.base.toml"
MCP_DIR = CODEX_DIR / "mcp_servers"
OUTPUT_CONFIG = CODEX_DIR / "config.toml"


def _read_toml(path: Path) -> str:
    text = path.read_text(encoding="utf-8").strip()
    tomllib.loads(text)
    return text


def render() -> str:
    parts = [
        "# .codex/config.toml",
        "# Generated by .codex/render_config.py.",
        "# Edit .codex/config.base.toml or .codex/mcp_servers/*.toml, then rerun:",
        "#   /home/amitbashyal/Documents/BNL-AiD2E/mcp-server/panda-mcp/bin/python .codex/render_config.py",
        "",
        _read_toml(BASE_CONFIG),
    ]

    for fragment in sorted(MCP_DIR.glob("*.toml")):
        parts.extend(["", _read_toml(fragment)])

    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    try:
        OUTPUT_CONFIG.write_text(render(), encoding="utf-8")
    except Exception as exc:
        print(f"Failed to render {OUTPUT_CONFIG}: {exc}", file=sys.stderr)
        return 1

    tomllib.loads(OUTPUT_CONFIG.read_text(encoding="utf-8"))
    print(f"Rendered {OUTPUT_CONFIG}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
